module.exports = [
  { number: 1, ar: "سورة الفاتحة", bm: "Kunci", en: "The Key", totalAyahs: 7 },
  { number: 2, ar: "سورة البقرة", bm: "Sapi Betina", en: "The Heifer", totalAyahs: 286 },
  { number: 3, ar: "سورة آل عمران", bm: "Keluarga Imran", en: "The Amramites", totalAyahs: 200 },
  { number: 4, ar: "سورة النساء", bm: "Perempuan", en: "Women", totalAyahs: 176 },
  { number: 5, ar: "سورة المائدة", bm: "Hidangan", en: "The Feast", totalAyahs: 120 },
  { number: 6, ar: "سورة الأنعام", bm: "Binatang Ternakan", en: "Livestock", totalAyahs: 165 },
  { number: 7, ar: "سورة الأعراف", bm: "Tempat Penungguan", en: "The Purgatory", totalAyahs: 206 },
  { number: 8, ar: "سورة الأنفال", bm: "Harta Peperangan", en: "The Spoils of War", totalAyahs: 75 },
  { number: 9, ar: "سورة براءة", bm: "Memberikan Kata Putus", en: "Ultimatum", totalAyahs: 129 },
  { number: 10, ar: "سورة يونس", bm: "Yunus", en: "Jonah", totalAyahs: 109 },
  { number: 11, ar: "سورة هود", bm: "Hud", en: "Hood", totalAyahs: 123 },
  { number: 12, ar: "سورة يوسف", bm: "Yusuf", en: "Joseph", totalAyahs: 111 },
  { number: 13, ar: "سورة الرعد", bm: "Guruh", en: "Thunder", totalAyahs: 43 },
  { number: 14, ar: "سورة إبراهيم", bm: "Ibrahim", en: "Abraham", totalAyahs: 52 },
  { number: 15, ar: "سورة الحجر", bm: "Lembah", en: "Al-Hijr Valley", totalAyahs: 99 },
  { number: 16, ar: "سورة النحل", bm: "Lebah", en: "The Bee", totalAyahs: 128 },
  { number: 17, ar: "سورة بنى إسرائيل", bm: "Keturunan Israil", en: "The Children of Israel", totalAyahs: 111 },
  { number: 18, ar: "سورة الكهف", bm: "Gua", en: "The Cave", totalAyahs: 110 },
  { number: 19, ar: "سورة مريم", bm: "Maryam", en: "Mary", totalAyahs: 98 },
  { number: 20, ar: "سورة طه", bm: "Tha Ha", en: "T.H.", totalAyahs: 135 },
  { number: 21, ar: "سورة الأنبياء", bm: "Para Nabi", en: "The Prophets", totalAyahs: 112 },
  { number: 22, ar: "سورة الحج", bm: "Menunaikan Haji", en: "Pilgrimage", totalAyahs: 78 },
  { number: 23, ar: "سورة المومنون", bm: "Orang Orang Yang Percaya", en: "The Believers", totalAyahs: 118 },
  { number: 24, ar: "سورة النور", bm: "Cahaya", en: "Light", totalAyahs: 64 },
  { number: 25, ar: "سورة الفرقان", bm: "Buku Perundangan", en: "The Statute Book", totalAyahs: 77 },
  { number: 26, ar: "سورة الشعراء", bm: "Penyair Penyair", en: "The Poets", totalAyahs: 227 },
  { number: 27, ar: "سورة النمل", bm: "Semut", en: "The Ant", totalAyahs: 93 },
  { number: 28, ar: "سورة القصص", bm: "Sejarah", en: "History", totalAyahs: 88 },
  { number: 29, ar: "سورة العنكبوت", bm: "Laba Laba", en: "The Spider", totalAyahs: 69 },
  { number: 30, ar: "سورة الروم", bm: "Orang Orang Rom", en: "The Romans", totalAyahs: 60 },
  { number: 31, ar: "سورة لقمان", bm: "Luqman", en: "Luqmaan", totalAyahs: 34 },
  { number: 32, ar: "سورة السجدة", bm: "Sujud", en: "Prostration", totalAyahs: 30 },
  { number: 33, ar: "سورة الأحزاب", bm: "Parti Parti", en: "The Parties", totalAyahs: 73 },
  { number: 34, ar: "سورة سبأ", bm: "Sheba", en: "Sheba", totalAyahs: 54 },
  { number: 35, ar: "سورة فاطر", bm: "Yang Meinsiasikan Ciptaan", en: "Initiator", totalAyahs: 45 },
  { number: 36, ar: "سورة يس", bm: "Ya Sin", en: "Y.S.", totalAyahs: 83 },
  { number: 37, ar: "سورة الصافات", bm: "Penyusun Penyusun", en: "The Arrangers", totalAyahs: 182 },
  { number: 38, ar: "سورة ص", bm: "Saad", en: "S.", totalAyahs: 88 },
  { number: 39, ar: "سورة الزمر", bm: "Kumpulan Orang Ramai", en: "The Throngs", totalAyahs: 75 },
  { number: 40, ar: "سورة غافر", bm: "Pengampun", en: "Forgiver", totalAyahs: 85 },
  { number: 41, ar: "سورة فصلت", bm: "Perincian", en: "Detailed", totalAyahs: 54 },
  { number: 42, ar: "سورة الشورى", bm: "Perundingan", en: "Consultation", totalAyahs: 53 },
  { number: 43, ar: "سورة الزخرف", bm: "Barang Barang Perhiasan", en: "Ornaments", totalAyahs: 89 },
  { number: 44, ar: "سورة الدخان", bm: "Asap", en: "Smoke", totalAyahs: 59 },
  { number: 45, ar: "سورة الجاثية", bm: "Berlutut", en: "Kneeling", totalAyahs: 37 },
  { number: 46, ar: "سورة الأحقاق", bm: "Bukit Pasir", en: "The Dunes", totalAyahs: 35 },
  { number: 47, ar: "سورة محمد", bm: "Muhammad", en: "Muhammad", totalAyahs: 38 },
  { number: 48, ar: "سورة الفتح", bm: "Kemenangan", en: "Victory", totalAyahs: 29 },
  { number: 49, ar: "سورة الحجرات", bm: "Dinding Dinding", en: "The Walls", totalAyahs: 18 },
  { number: 50, ar: "سورة ق", bm: "Qaf", en: "Q.", totalAyahs: 45 },
  { number: 51, ar: "سورة الذاريات", bm: "Penggerak Penggerak Angin", en: "Drivers of the Winds", totalAyahs: 60 },
  { number: 52, ar: "سورة الطور", bm: "Bukit Sinai", en: "Mount Sinai", totalAyahs: 49 },
  { number: 53, ar: "سورة النجم", bm: "Bintang Bintang", en: "The Stars", totalAyahs: 62 },
  { number: 54, ar: "سورة القمر", bm: "Bulan", en: "The Moon", totalAyahs: 55 },
  { number: 55, ar: "سورة الرحمن", bm: "Yang Maha Pengasih", en: "Most Gracious", totalAyahs: 78 },
  { number: 56, ar: "سورة الواقعة", bm: "Yang Tidak Boleh Di-Elakkan Lagi", en: "The Inevitable", totalAyahs: 96 },
  { number: 57, ar: "سورة الحديد", bm: "Besi", en: "Iron", totalAyahs: 29 },
  { number: 58, ar: "سورة المجادلة", bm: "Perdebatan", en: "The Debate", totalAyahs: 22 },
  { number: 59, ar: "سورة الحشر", bm: "Pengusiran beramai Ramai", en: "Exodus", totalAyahs: 24 },
  { number: 60, ar: "سورة الممتحنة", bm: "Ujian", en: "The Test", totalAyahs: 13 },
  { number: 61, ar: "سورة الصف", bm: "Barisan", en: "The Column", totalAyahs: 14 },
  { number: 62, ar: "سورة الجمعة", bm: "Juma'at", en: "Friday", totalAyahs: 11 },
  { number: 63, ar: "سورة المنافقون", bm: "Orang Orang Hypokrit", en: "The Hypocrites", totalAyahs: 11 },
  { number: 64, ar: "سورة التغابن", bm: "Saling Menuduh", en: "Mutual Blaming", totalAyahs: 18 },
  { number: 65, ar: "سورة الطلاق", bm: "Perceraian", en: "Divorce", totalAyahs: 12 },
  { number: 66, ar: "سورة التحريم", bm: "Larangan", en: "Prohibition", totalAyahs: 12 },
  { number: 67, ar: "سورة الملك", bm: "Yang Menguasai Kerajaan Kerajaan", en: "Kingship", totalAyahs: 30 },
  { number: 68, ar: "سورة القلم", bm: "Pena", en: "The Pen", totalAyahs: 52 },
  { number: 69, ar: "سورة الحاقة", bm: "Tidak dapat Di-Pertikaikan", en: "Incontestable", totalAyahs: 52 },
  { number: 70, ar: "سورة المعارج", bm: "Ketinggian", en: "The Heights", totalAyahs: 44 },
  { number: 71, ar: "سورة نوح", bm: "Nuh", en: "Noah", totalAyahs: 28 },
  { number: 72, ar: "سورة الجن", bm: "Jin", en: "Jinns", totalAyahs: 28 },
  { number: 73, ar: "سورة المزمل", bm: "Yang Berselubung", en: "Cloaked", totalAyahs: 20 },
  { number: 74, ar: "سورة المدثر", bm: "Rahsia Yang Tersembunyi", en: "The Hidden Secret", totalAyahs: 56 },
  { number: 75, ar: "سورة القيامة", bm: "Hari Kebangkitan", en: "Resurrection", totalAyahs: 40 },
  { number: 76, ar: "سورة الإنسان", bm: "Manusia", en: "The Human", totalAyahs: 31 },
  { number: 77, ar: "سورة المرسلاة", bm: "Penghantaran", en: "Dispatched", totalAyahs: 50 },
  { number: 78, ar: "سورة النبأ", bm: "Peristiwa", en: "The Event", totalAyahs: 40 },
  { number: 79, ar: "سورة النازعات", bm: "Peragut", en: "The Snatchers", totalAyahs: 46 },
  { number: 80, ar: "سورة عبس", bm: "Berkerut Dahi", en: "He Frowned", totalAyahs: 42 },
  { number: 81, ar: "سورة التكوير", bm: "Menggulung", en: "The Rolling", totalAyahs: 29 },
  { number: 82, ar: "سورة الإنفطار", bm: "Menghancurkan", en: "The Shattering", totalAyahs: 19 },
  { number: 83, ar: "سورة المطففين", bm: "Para Penipu", en: "The Cheaters", totalAyahs: 36 },
  { number: 84, ar: "سورة الإنشقاق", bm: "Perpecahan", en: "The Rupture", totalAyahs: 25 },
  { number: 85, ar: "سورة البروج", bm: "Bimasakti Bimasakti", en: "The Galaxies", totalAyahs: 22 },
  { number: 86, ar: "سورة الطارق", bm: "Bintang Yang Terang", en: "The Bright Star", totalAyahs: 17 },
  { number: 87, ar: "سورة الأعلى", bm: "Yang Maha Tinggi", en: "The Most High", totalAyahs: 19 },
  { number: 88, ar: "سورة الغاشية", bm: "Peristiwa Yang Amat Sangat", en: "Overwhelming", totalAyahs: 26 },
  { number: 89, ar: "سورة الفجر", bm: "Subuh", en: "Dawn", totalAyahs: 30 },
  { number: 90, ar: "سورة البلد", bm: "Bandar", en: "The Town", totalAyahs: 20 },
  { number: 91, ar: "سورة الشمس", bm: "Matahari", en: "The Sun", totalAyahs: 15 },
  { number: 92, ar: "سورة الليل", bm: "Malam", en: "The Night", totalAyahs: 21 },
  { number: 93, ar: "سورة الضحى", bm: "Pagi", en: "The Forenoon", totalAyahs: 11 },
  { number: 94, ar: "سورة الشرح", bm: "Mengawal Perasaan Marah", en: "Cooling the Temper", totalAyahs: 8 },
  { number: 95, ar: "سورة التين", bm: "Buah Tin", en: "The Fig", totalAyahs: 8 },
  { number: 96, ar: "سورة العلق", bm: "Embrio", en: "The Embryo", totalAyahs: 19 },
  { number: 97, ar: "سورة القدر", bm: "Destini", en: "Destiny", totalAyahs: 5 },
  { number: 98, ar: "سورة البينة", bm: "Bukti", en: "Proof", totalAyahs: 8 },
  { number: 99, ar: "سورة الزلزلة", bm: "Gempa", en: "The Quake", totalAyahs: 8 },
  { number: 100, ar: "سورة العاديات", bm: "Berlari Kencang", en: "The Gallopers", totalAyahs: 11 },
  { number: 101, ar: "سورة القارعة", bm: "Memeranjatkan", en: "The Shocker", totalAyahs: 11 },
  { number: 102, ar: "سورة التكاثر", bm: "Mengumpulkan", en: "Hoarding", totalAyahs: 8 },
  { number: 103, ar: "سورة العصر", bm: "Petang Hari", en: "The Afternoon", totalAyahs: 3 },
  { number: 104, ar: "سورة الهمزة", bm: "Pengumpat", en: "The Backbiter", totalAyahs: 9 },
  { number: 105, ar: "سورة الفيل", bm: "Gajah", en: "The Elephant", totalAyahs: 5 },
  { number: 106, ar: "سورة قريش", bm: "Kaum Quraish", en: "Quraish Tribe", totalAyahs: 4 },
  { number: 107, ar: "سورة الماعون", bm: "Derma", en: "Charity", totalAyahs: 7 },
  { number: 108, ar: "سورة الكوثر", bm: "Kemewahan", en: "Bounty", totalAyahs: 3 },
  { number: 109, ar: "سورة الكافرون", bm: "Pengingkar Pengingkar", en: "The Disbelievers", totalAyahs: 6 },
  { number: 110, ar: "سورة النصر", bm: "Kemenangan", en: "Triumph", totalAyahs: 3 },
  { number: 111, ar: "سورة المسد", bm: "Duri Duri", en: "Thorns", totalAyahs: 5 },
  { number: 112, ar: "سورة الإخلاص", bm: "Dengan Segala Kebenaran", en: "Absoluteness", totalAyahs: 4 },
  { number: 113, ar: "سورة الفلق", bm: "Matahari Terbit", en: "Daybreak", totalAyahs: 5 },
  { number: 114, ar: "سورة الناس", bm: "Manusia", en: "People", totalAyahs: 6 },
];
