module.exports = [
  { number: 1, ar: "الفاتحة", bm: "Al-Fatihah", en: "The Opening", totalAyahs: 7 },
  { number: 2, ar: "البقرة", bm: "Al-Baqarah", en: "The Cow", totalAyahs: 286 },
  { number: 3, ar: "آل عمران", bm: "Ali 'Imran", en: "Family of Imran", totalAyahs: 200 },
  { number: 4, ar: "النساء", bm: "An-Nisa'", en: "The Women", totalAyahs: 176 },
  { number: 5, ar: "المائدة", bm: "Al-Ma'idah", en: "The Table Spread", totalAyahs: 120 },
  { number: 6, ar: "الأنعام", bm: "Al-An'am", en: "The Cattle", totalAyahs: 165 },
  { number: 7, ar: "الأعراف", bm: "Al-A'raf", en: "The Heights", totalAyahs: 206 },
  { number: 8, ar: "الأنفال", bm: "Al-Anfal", en: "The Spoils of War", totalAyahs: 75 },
  { number: 9, ar: "التوبة", bm: "At-Tawbah", en: "The Repentance", totalAyahs: 129 },
  { number: 10, ar: "يونس", bm: "Yunus", en: "Jonah", totalAyahs: 109 },
  { number: 11, ar: "هود", bm: "Hud", en: "Hud", totalAyahs: 123 },
  { number: 12, ar: "يوسف", bm: "Yusuf", en: "Joseph", totalAyahs: 111 },
  { number: 13, ar: "الرعد", bm: "Ar-Ra'd", en: "The Thunder", totalAyahs: 43 },
  { number: 14, ar: "ابراهيم", bm: "Ibrahim", en: "Abraham", totalAyahs: 52 },
  { number: 15, ar: "الحجر", bm: "Al-Hijr", en: "The Rocky Tract", totalAyahs: 99 },
  { number: 16, ar: "النحل", bm: "An-Nahl", en: "The Bee", totalAyahs: 128 },
  { number: 17, ar: "الإسراء", bm: "Al-Isra'", en: "The Night Journey", totalAyahs: 111 },
  { number: 18, ar: "الكهف", bm: "Al-Kahf", en: "The Cave", totalAyahs: 110 },
  { number: 19, ar: "مريم", bm: "Maryam", en: "Mary", totalAyahs: 98 },
  { number: 20, ar: "طه", bm: "Ta-Ha", en: "Ta-Ha", totalAyahs: 135 },
  { number: 21, ar: "الأنبياء", bm: "Al-Anbiya'", en: "The Prophets", totalAyahs: 112 },
  { number: 22, ar: "الحج", bm: "Al-Hajj", en: "The Pilgrimage", totalAyahs: 78 },
  { number: 23, ar: "المؤمنون", bm: "Al-Mu'minun", en: "The Believers", totalAyahs: 118 },
  { number: 24, ar: "النور", bm: "An-Nur", en: "The Light", totalAyahs: 64 },
  { number: 25, ar: "الفرقان", bm: "Al-Furqan", en: "The Criterion", totalAyahs: 77 },
  { number: 26, ar: "الشعراء", bm: "Ash-Shu'ara'", en: "The Poets", totalAyahs: 227 },
  { number: 27, ar: "النمل", bm: "An-Naml", en: "The Ant", totalAyahs: 93 },
  { number: 28, ar: "القصص", bm: "Al-Qasas", en: "The Stories", totalAyahs: 88 },
  { number: 29, ar: "العنكبوت", bm: "Al-'Ankabut", en: "The Spider", totalAyahs: 69 },
  { number: 30, ar: "الروم", bm: "Ar-Rum", en: "The Romans", totalAyahs: 60 },
  { number: 31, ar: "لقمان", bm: "Luqman", en: "Luqman", totalAyahs: 34 },
  { number: 32, ar: "السجدة", bm: "As-Sajdah", en: "The Prostration", totalAyahs: 30 },
  { number: 33, ar: "الأحزاب", bm: "Al-Ahzab", en: "The Combined Forces", totalAyahs: 73 },
  { number: 34, ar: "سبإ", bm: "Saba'", en: "Sheba", totalAyahs: 54 },
  { number: 35, ar: "فاطر", bm: "Fatir", en: "Originator", totalAyahs: 45 },
  { number: 36, ar: "يس", bm: "Ya-Sin", en: "Ya-Sin", totalAyahs: 83 },
  { number: 37, ar: "الصافات", bm: "As-Saffat", en: "Those Who Set the Ranks", totalAyahs: 182 },
  { number: 38, ar: "ص", bm: "Sad", en: "Sad", totalAyahs: 88 },
  { number: 39, ar: "الزمر", bm: "Az-Zumar", en: "The Groups", totalAyahs: 75 },
  { number: 40, ar: "غافر", bm: "Ghafir", en: "The Forgiver", totalAyahs: 85 },
  { number: 41, ar: "فصلت", bm: "Fussilat", en: "Explained in Detail", totalAyahs: 54 },
  { number: 42, ar: "الشورى", bm: "Ash-Shuraa", en: "The Consultation", totalAyahs: 53 },
  { number: 43, ar: "الزخرف", bm: "Az-Zukhruf", en: "The Gold Adornments", totalAyahs: 89 },
  { number: 44, ar: "الدخان", bm: "Ad-Dukhan", en: "The Smoke", totalAyahs: 59 },
  { number: 45, ar: "الجاثية", bm: "Al-Jathiyah", en: "The Crouching", totalAyahs: 37 },
  { number: 46, ar: "الأحقاف", bm: "Al-Ahqaf", en: "The Wind-Curved Sandhills", totalAyahs: 35 },
  { number: 47, ar: "محمد", bm: "Muhammad", en: "Muhammad", totalAyahs: 38 },
  { number: 48, ar: "الفتح", bm: "Al-Fath", en: "The Victory", totalAyahs: 29 },
  { number: 49, ar: "الحجرات", bm: "Al-Hujurat", en: "The Rooms", totalAyahs: 18 },
  { number: 50, ar: "ق", bm: "Qaf", en: "Qaf", totalAyahs: 45 },
  { number: 51, ar: "الذاريات", bm: "Adh-Dhariyat", en: "The Winnowing Winds", totalAyahs: 60 },
  { number: 52, ar: "الطور", bm: "At-Tur", en: "The Mount", totalAyahs: 49 },
  { number: 53, ar: "النجم", bm: "An-Najm", en: "The Star", totalAyahs: 62 },
  { number: 54, ar: "القمر", bm: "Al-Qamar", en: "The Moon", totalAyahs: 55 },
  { number: 55, ar: "الرحمن", bm: "Ar-Rahman", en: "The Most Compassionate", totalAyahs: 78 },
  { number: 56, ar: "الواقعة", bm: "Al-Waqi'ah", en: "The Inevitable", totalAyahs: 96 },
  { number: 57, ar: "الحديد", bm: "Al-Hadid", en: "The Iron", totalAyahs: 29 },
  { number: 58, ar: "المجادلة", bm: "Al-Mujadilah", en: "The Pleading Woman", totalAyahs: 22 },
  { number: 59, ar: "الحشر", bm: "Al-Hashr", en: "The Exile", totalAyahs: 24 },
  { number: 60, ar: "الممتحنة", bm: "Al-Mumtahanah", en: "She That Is To Be Examined", totalAyahs: 13 },
  { number: 61, ar: "الصف", bm: "As-Saff", en: "The Ranks", totalAyahs: 14 },
  { number: 62, ar: "الجمعة", bm: "Al-Jumu'ah", en: "The Congregation", totalAyahs: 11 },
  { number: 63, ar: "المنافقون", bm: "Al-Munafiqun", en: "The Hypocrites", totalAyahs: 11 },
  { number: 64, ar: "التغابن", bm: "At-Taghabun", en: "The Mutual Disillusion", totalAyahs: 18 },
  { number: 65, ar: "الطلاق", bm: "At-Talaq", en: "The Divorce", totalAyahs: 12 },
  { number: 66, ar: "التحريم", bm: "At-Tahrim", en: "The Prohibition", totalAyahs: 12 },
  { number: 67, ar: "الملك", bm: "Al-Mulk", en: "The Sovereignty", totalAyahs: 30 },
  { number: 68, ar: "القلم", bm: "Al-Qalam", en: "The Pen", totalAyahs: 52 },
  { number: 69, ar: "الحاقة", bm: "Al-Haqqah", en: "The Reality", totalAyahs: 52 },
  { number: 70, ar: "المعارج", bm: "Al-Ma'arij", en: "The Ascending Stairways", totalAyahs: 44 },
  { number: 71, ar: "نوح", bm: "Nuh", en: "Noah", totalAyahs: 28 },
  { number: 72, ar: "الجن", bm: "Al-Jinn", en: "The Jinn", totalAyahs: 28 },
  { number: 73, ar: "المزمل", bm: "Al-Muzzammil", en: "The Enshrouded One", totalAyahs: 20 },
  { number: 74, ar: "المدثر", bm: "Al-Muddaththir", en: "The Cloaked One", totalAyahs: 56 },
  { number: 75, ar: "القيامة", bm: "Al-Qiyamah", en: "The Resurrection", totalAyahs: 40 },
  { number: 76, ar: "الانسان", bm: "Al-Insan", en: "The Human", totalAyahs: 31 },
  { number: 77, ar: "المرسلات", bm: "Al-Mursalat", en: "Those Sent Forth", totalAyahs: 50 },
  { number: 78, ar: "النبإ", bm: "An-Naba'", en: "The Tidings", totalAyahs: 40 },
  { number: 79, ar: "النازعات", bm: "An-Nazi'at", en: "Those Who Drag Forth", totalAyahs: 46 },
  { number: 80, ar: "عبس", bm: "'Abasa", en: "He Frowned", totalAyahs: 42 },
  { number: 81, ar: "التكوير", bm: "At-Takwir", en: "The Overthrowing", totalAyahs: 29 },
  { number: 82, ar: "الإنفطار", bm: "Al-Infitar", en: "The Cleaving", totalAyahs: 19 },
  { number: 83, ar: "المطففين", bm: "Al-Mutaffifin", en: "Defrauding", totalAyahs: 36 },
  { number: 84, ar: "الإنشقاق", bm: "Al-Inshiqaq", en: "The Splitting Open", totalAyahs: 25 },
  { number: 85, ar: "البروج", bm: "Al-Buruj", en: "The Mansions of the Stars", totalAyahs: 22 },
  { number: 86, ar: "الطارق", bm: "At-Tariq", en: "The Nightcomer", totalAyahs: 17 },
  { number: 87, ar: "الأعلى", bm: "Al-A'la", en: "The Most High", totalAyahs: 19 },
  { number: 88, ar: "الغاشية", bm: "Al-Ghashiyah", en: "The Overwhelming", totalAyahs: 26 },
  { number: 89, ar: "الفجر", bm: "Al-Fajr", en: "The Dawn", totalAyahs: 30 },
  { number: 90, ar: "البلد", bm: "Al-Balad", en: "The City", totalAyahs: 20 },
  { number: 91, ar: "الشمس", bm: "Ash-Shams", en: "The Sun", totalAyahs: 15 },
  { number: 92, ar: "الليل", bm: "Al-Layl", en: "The Night", totalAyahs: 21 },
  { number: 93, ar: "الضحى", bm: "Ad-Duhaa", en: "The Morning Brightness", totalAyahs: 11 },
  { number: 94, ar: "الشرح", bm: "Ash-Sharh", en: "The Relief", totalAyahs: 8 },
  { number: 95, ar: "التين", bm: "At-Tin", en: "The Fig", totalAyahs: 8 },
  { number: 96, ar: "العلق", bm: "Al-'Alaq", en: "The Clinging Clot", totalAyahs: 19 },
  { number: 97, ar: "القدر", bm: "Al-Qadr", en: "The Power", totalAyahs: 5 },
  { number: 98, ar: "البينة", bm: "Al-Bayyinah", en: "The Clear Proof", totalAyahs: 8 },
  { number: 99, ar: "الزلزلة", bm: "Az-Zalzalah", en: "The Earthquake", totalAyahs: 8 },
  { number: 100, ar: "العاديات", bm: "Al-'Adiyat", en: "The Courser", totalAyahs: 11 },
  { number: 101, ar: "القارعة", bm: "Al-Qari'ah", en: "The Calamity", totalAyahs: 11 },
  { number: 102, ar: "التكاثر", bm: "At-Takathur", en: "Rivalry in World Increase", totalAyahs: 8 },
  { number: 103, ar: "العصر", bm: "Al-'Asr", en: "The Declining Day", totalAyahs: 3 },
  { number: 104, ar: "الهمزة", bm: "Al-Humazah", en: "The Traducer", totalAyahs: 9 },
  { number: 105, ar: "الفيل", bm: "Al-Fil", en: "The Elephant", totalAyahs: 5 },
  { number: 106, ar: "قريش", bm: "Quraysh", en: "Quraysh", totalAyahs: 4 },
  { number: 107, ar: "الماعون", bm: "Al-Ma'un", en: "Small Kindnesses", totalAyahs: 7 },
  { number: 108, ar: "الكوثر", bm: "Al-Kawthar", en: "Abundance", totalAyahs: 3 },
  { number: 109, ar: "الكافرون", bm: "Al-Kafirun", en: "The Disbelievers", totalAyahs: 6 },
  { number: 110, ar: "النصر", bm: "An-Nasr", en: "Divine Support", totalAyahs: 3 },
  { number: 111, ar: "المسد", bm: "Al-Masad", en: "The Palm Fiber", totalAyahs: 5 },
  { number: 112, ar: "الإخلاص", bm: "Al-Ikhlas", en: "Sincerity", totalAyahs: 4 },
  { number: 113, ar: "الفلق", bm: "Al-Falaq", en: "The Daybreak", totalAyahs: 5 },
  { number: 114, ar: "الناس", bm: "An-Nas", en: "Mankind", totalAyahs: 6 },
];
