export const bmTranslatedSuraNames = {
  1: "Kunci",
  2: "Sapi Betina",
  3: "Keluarga Imran",
  4: "Perempuan",
  5: "Hidangan",
  6: "Binatang Ternakan",
  7: "Tempat Penungguan",
  8: "Harta Peperangan",
  9: "Memberikan Kata Putus",
  10: "Yunus",
  11: "Hud",
  12: "Yusuf",
  13: "Guruh",
  14: "Ibrahim",
  15: "Lembah",
  16: "Lebah",
  17: "Keturunan Israil",
  18: "Gua",
  19: "Maryam",
  20: "Tha Ha",
  21: "Para Nabi",
  22: "Menunaikan Haji",
  23: "Orang Orang Yang Percaya",
  24: "Cahaya",
  25: "Buku Perundangan",
  26: "Penyair Penyair",
  27: "Semut",
  28: "Sejarah",
  29: "Laba Laba",
  30: "Orang Orang Rom",
  31: "Luqman",
  32: "Sujud",
  33: "Parti Parti",
  34: "Sheba",
  35: "Yang Meinsiasikan Ciptaan",
  36: "Ya Sin",
  37: "Penyusun Penyusun",
  38: "Saad",
  39: "Kumpulan Orang Ramai",
  40: "Pengampun",
  41: "Perincian",
  42: "Perundingan",
  43: "Barang Barang Perhiasan",
  44: "Asap",
  45: "Berlutut",
  46: "Bukit Pasir",
  47: "Muhammad",
  48: "Kemenangan",
  49: "Dinding Dinding",
  50: "Qaf",
  51: "Penggerak Penggerak Angin",
  52: "Bukit Sinai",
  53: "Bintang Bintang",
  54: "Bulan",
  55: "Yang Maha Pengasih",
  56: "Yang Tidak Boleh Di-Elakkan Lagi",
  57: "Besi",
  58: "Perdebatan",
  59: "Pengusiran beramai Ramai",
  60: "Ujian",
  61: "Barisan",
  62: "Juma'at",
  63: "Orang Orang Hypokrit",
  64: "Saling Menuduh",
  65: "Perceraian",
  66: "Larangan",
  67: "Yang Menguasai Kerajaan Kerajaan",
  68: "Pena",
  69: "Tidak dapat Di-Pertikaikan",
  70: "Ketinggian",
  71: "Nuh",
  72: "Jin",
  73: "Yang Berselubung",
  74: "Rahsia Yang Tersembunyi",
  75: "Hari Kebangkitan",
  76: "Manusia",
  77: "Penghantaran",
  78: "Peristiwa",
  79: "Peragut",
  80: "Berkerut Dahi",
  81: "Menggulung",
  82: "Menghancurkan",
  83: "Para Penipu",
  84: "Perpecahan",
  85: "Bimasakti Bimasakti",
  86: "Bintang Yang Terang",
  87: "Yang Maha Tinggi",
  88: "Peristiwa Yang Amat Sangat",
  89: "Subuh",
  90: "Bandar",
  91: "Matahari",
  92: "Malam",
  93: "Pagi",
  94: "Mengawal Perasaan Marah",
  95: "Buah Tin",
  96: "Embrio",
  97: "Destini",
  98: "Bukti",
  99: "Gempa",
  100: "Berlari Kencang",
  101: "Memeranjatkan",
  102: "Mengumpulkan",
  103: "Petang Hari",
  104: "Pengumpat",
  105: "Gajah",
  106: "Kaum Quraish",
  107: "Derma",
  108: "Kemewahan",
  109: "Pengingkar Pengingkar",
  110: "Kemenangan",
  111: "Duri Duri",
  112: "Dengan Segala Kebenaran",
  113: "Matahari Terbit",
  114: "Manusia",
};
